spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port:
    - "8080:8080"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: backend
    description: Store Api
    version: 1.0.0